---
title: "Mini Project 3"
author: "Chelsey Chen, Yuri Furukawa"
date: "April 15, 2018"
output:
  html_document:
    code_folding: show
---

```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(macleish)
library(RColorBrewer)
library(leaflet)
library(sf)
```

## Import Elevation Contour Data
```{r, eval = FALSE}
# Elevation Data: MassGIS Data: Elevation Contours (1:250,000)
url <- "http://download.massgis.digital.mass.gov/shapefiles/state/contours250k.zip"
local_file <- basename(url)
download.file(url, destfile = local_file)
unzip(local_file, exdir = "elevation")
```

##Data Wrangling 
```{r, message = FALSE, warning = FALSE}
#elevation <- st_read("elevation/CONTOURS250K_ARC.shp")

dsn <- path.expand("elevation")
dsn
list.files(dsn)
st_layers(dsn)
elevation <- read_sf(dsn)

trails <- macleish_layers[["trails"]]
trails <- trails %>%
  mutate(LENGTH = st_length(geometry)) %>%
  group_by(name) %>%
  summarize(num_segments = n(), 
            total_length = sum(LENGTH)) %>%
  arrange(desc(total_length))

#elevation <- elevation %>%
#  arrange(desc(CONTOUR_FT))s

# Check the Coordinate Reference System of the elevation layer
elevation %>%
  st_crs()

# Projection for the elevation layer
elevation <- elevation %>%
  st_transform(4326)


# Join the elevation layer to macleish trails layers and make that as a new dataframe

my_data <- trails %>%
  st_intersection(elevation) %>%
  select(name,total_length, CONTOUR_FT, geometry) %>%
  group_by(name,total_length)%>%
  summarize(change_elevation = max(CONTOUR_FT)-min(CONTOUR_FT)) %>%
  mutate(score_elevation = ifelse(change_elevation %in% 0:40, 0,
                                  ifelse(change_elevation %in% 40:80, 1,2)),
         score_length=ifelse(total_length < 1000, 0,
                             ifelse(total_length > 1000 &&
                                    total_length < 2000, 1,2)),
         total_score = score_elevation + score_length)
```

##Data Visualizations
```{r, message = FALSE, warning = FALSE}
trail_pal <- colorNumeric("viridis", 
                  my_data$total_score)
my_data$geometry <- st_cast(my_data$geometry, "LINESTRING")

leaflet() %>%
  addTiles() %>% 
  addPolylines(data = my_data,
               color = ~trail_pal(total_length),
               popup = ~name,
              fillOpacity = 0.8, weight = 0.1)

```

```{r}
leaflet() %>%
  addTiles() %>% 
  addPolylines(data = my_data)
```


## Not execute
```{r}
#-----------------------------
  proj4_aea <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

road_buffer <- macleish_layers[["trails"]] %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 10) %>%
  st_transform(4326)

leaflet() %>%
  addTiles() %>%
  addPolylines(data = macleish_layers[["trails"]], 
               weight = 1, color = "black") %>%
  addPolygons(data = road_buffer) 
```

